<?php

namespace Umg\VotacionBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CarreraCursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CarreraCursoRepository extends EntityRepository
{
	public function findCarrera($id)
    {
        return $this->getEntityManager()
            ->createQueryBuilder()
            ->select('e')
            ->from('UmgVotacionBundle:CarreraCurso', 'e')
            ->where('e.Alumno_id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult()
            ;
    }
}
