services:
#    umg_votacion.example:
#        class: Umg\VotacionBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
sonata.admin.jornada:
        class: Umg\VotacionBundle\Admin\JornadaAdmin
        tags:
            - { name: sonata.admin, manager_type: orm, group: Administración, label: Jornada }
        arguments: [null, Umg\VotacionBundle\Entity\Jornada, UmgVotacionBundle:JornadaAdmin]